{% set name = "dinghy" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dinghy-{{ version }}.tar.gz
  sha256: dea20238d49e5cc860f8052090576a26d0e60b86a330c9cac306bc5f3a9dad24

build:
  entry_points:
    - dinghy = dinghy.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiofiles >=0.8
    - aiohttp >3
    - click >8
    - click-log >0.3
    - emoji
    - glom
    - jinja2 >3
    - pyyaml >=6

test:
  imports:
    - dinghy
  commands:
    - pip check
    - dinghy --help
  requires:
    - pip

about:
  home: https://github.com/nedbat/dinghy
  summary: Dinghy daily digest tool
  dev_url: https://github.com/nedbat/dinghy
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shwina
